// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd5HT1MDNaxtSt5PaEuOfjmvvE8NVRIVQ',
    appId: '1:755819704788:web:1b47cb2fc20ef24defa641',
    messagingSenderId: '755819704788',
    projectId: 'chat-app-230f7',
    authDomain: 'chat-app-230f7.firebaseapp.com',
    storageBucket: 'chat-app-230f7.appspot.com',
    measurementId: 'G-259CJQGK8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLK422dqosi1QOuo9vvZLjVDzr_WWLU9w',
    appId: '1:755819704788:android:462f4d5734b0d5b1efa641',
    messagingSenderId: '755819704788',
    projectId: 'chat-app-230f7',
    storageBucket: 'chat-app-230f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnxtRvDVd4qSD6gmEMhj941U4-XpbAbpo',
    appId: '1:755819704788:ios:937d448e2121236aefa641',
    messagingSenderId: '755819704788',
    projectId: 'chat-app-230f7',
    storageBucket: 'chat-app-230f7.appspot.com',
    iosClientId: '755819704788-4n52iuga9t4c4judh5odj9h5m6jqe9qa.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnxtRvDVd4qSD6gmEMhj941U4-XpbAbpo',
    appId: '1:755819704788:ios:937d448e2121236aefa641',
    messagingSenderId: '755819704788',
    projectId: 'chat-app-230f7',
    storageBucket: 'chat-app-230f7.appspot.com',
    iosClientId: '755819704788-4n52iuga9t4c4judh5odj9h5m6jqe9qa.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
